services:
  - type: web
    name: g2g-telegram-notifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python g2g-render-solution.py
    plan: free
    envVars:
      - key: RENDER
        value: true
      - key: TELEGRAM_TOKEN
        value: 7930326081:AAEciV70HcbcJuonGLli_RnQrT_tx9z-4-4
      - key: TELEGRAM_CHAT_ID
        value: 1356415148
      - key: G2G_USERNAME
        sync: false
      - key: G2G_PASSWORD
        sync: false
